baseurl = "http://choly.ca/"
languageCode = "en-us"
title = "Choly's Blog"
theme = "hyde"
googleAnalytics = "UA-36797023-1"

[markup]
  [markup.highlight]
    style = "tango"

[params]
  description = "Documented Procrastination"
  disqusShortname = "choly"

[[menu.main]]
  name = "Github"
  url = "https://github.com/icholy"

[[menu.main]]
  name = "Stack Overflow"
  url = "http://stackoverflow.com/users/215969/ilia-choly"
    

  
